---
addons:
  apt:
    packages:
      - libcurl4-gnutls-dev
before_script:
  - "cmake -H. -Bbuild_gcc -DCMAKE_BUILD_TYPE=Release -G\"Unix Makefiles\""
cache: apt
compiler:
  - gcc
dist: trusty
language: cpp
os:
  - linux
script:
  - "if [ \"$CXX\" = \"g++\" ]; then cmake --build build_gcc; fi"
sudo: required

